ecom_main/urls.py
from django.contrib import admin
from django.urls import (path, include)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('menu.urls'))
]

menu/urls.py
from django.urls import (path, include)
from . views import (home, service, about)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', home, name='home'),
    path('about', about, name='about'),
    path('services', service, name='service'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/models.py
from django.db import models

class Menu(models.Model):
    name = models.CharField(max_length=50)
    parent_menu = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    url = models.CharField(max_length=200, blank=True)
    
    def __str__(self):
        return self.name

product/models.py
from django.db import models
from menu.models import Menu


# Create your models here.
class Image(models.Model):
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.image.name
    
    
class product(models.Model):
    name        = models.CharField(max_length=50, null=False, blank=False)
    details     = models.CharField(max_length=1000, null=True, blank=True)
    price       = models.IntegerField(null=True, blank=True)
    discount    = models.IntegerField(null=True, blank=True)
    menu        = models.ForeignKey(Menu, on_delete=models.CASCADE)
    images      = models.ManyToManyField(Image)
    
    def __str__(self):
            return self.name
        

menu/views.py
from django.shortcuts import render, redirect
from .models import Menu
from product.models import product

def home(request):
    menu_items = Menu.objects.all() # Retrieve all menu items from the database
    msg = f'web menu home'
    context = {
        'menu_items': menu_items,
        'msg': msg
    }
    return render(request, 'menu.html', context)


def service(request):
    menu_items = Menu.objects.all() 
    # Retrieve all menu items from the database
    msg = f'web menu service'
    context = {
        'menu_items': menu_items,
        'msg': msg
    }
    return render(request, 'menu.html', context)

def about(request):
    menu_items = Menu.objects.all()  # Retrieve all menu items from the database
    msg = f'web menu about'
    context = {
        'menu_items': menu_items,
        'msg': msg
    }
    return render(request, 'menu.html', context)

product/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <nav class="">
      <div class="container">
        <ul class="navbar-menu">
          {% for menu in menu_items %} {% if menu.parent_menu is null %}
          <li class="">
            <a class="" href="{% url menu.url %}">{{ menu.name }}</a>
            {% if menu.menu_set.all %}
            <ul>
              {% for submenu in menu.menu_set.all %}
              <li class="">
                <a class="" href="{% url submenu.url %}">{{ submenu.name }}</a>
                {% if submenu.menu_set.all %}
                <ul>
                  {% for subsubmenu in submenu.menu_set.all %}
                  <li class="">
                    <a class="" href="{% url subsubmenu.url %}">{{ subsubmenu.name }}</a>
                  </li>
                  <!-- Add more nested levels if needed -->
                  {% endfor %}
                </ul>
                {% endif %} {% endfor %}
              </li>
            </ul>
            {% endif %} {% endif %} {% endfor %}
          </li>
        </ul>
      </div>
    </nav>

    {% block template %}{% endblock template %}
  </body>
</html>

templates/menu.html
{% extends 'base.html' %} {% block template %}
<div class="container">
  <p>{{ msg }}</p>
</div>
{% endblock template %}